### ISSUE TITLE
Start profiling only when Client is ready

### ISSUE THREAD

**Issue by YuanmingLeee** [cap-ntu/ML-Model-CI#121]
#### Problem description
The container starts and the profiler fails to inter with the Docker container, as the model needs some time for loading.
Call profiler immediately after call sver will raise an error:
```
Traceback (most recent call last):
  File "/home/lym/.pycharm_helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/lym/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/hub/init_data.py", line 166, in <module>
    args.func(args)
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/hub/init_data.py", line 136, in export_model
    ModelExporter.ResNet50(framework)
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/hub/init_data.py", line 56, in ResNet50
    convert=export_trt
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/hub/manager.py", line 134, in register_model
    result = profiler.diagnose()
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/hub/profiler.py", line 48, in diagnose
    self.inspector.run_model(self.server_name)
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/metrics/benchmark/metric.py", line 87, in run_model
    self.start_infer_with_time(batch)
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/metrics/benchmark/metric.py", line 148, in start_infer_with_time
    self.make_request(batch_input)
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/hub/client/tfs_client.py", line 29, in make_request
    channel = grpc.insecure_channel(FLAGS.server)
  File "/home/lym/anaconda3/envs/modelci/lib/python3.7/site-packages/tensorflow_core/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/lym/anaconda3/envs/modelci/lib/python3.7/site-packages/absl/flags/_flagvalues.py", line 633, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'model'
```

#### Steps to Reproduce the Problem
```python
client = CVTFSClient(repeat_data=test_img_bytes, batch_size=32, batch_num=100, asynchronous=False)
container = serve(save_path=model_dir, device='cuda')
profiler = Profiler(model_info=model, server_name=container.name, inspector=client)
result = profiler.diagnose()
container.stop()
```

#### Expected Behavior
Profile successfully

#### Other Information 
Shall add a check in the profiler diagnose function, see if the model finishes loading

**Comment by huangyz0918** [comment]
> absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'model'

This error looks like from argument parsing
