### ISSUE TITLE
Current profiler fails in profiling on CPU

### ISSUE THREAD

**Issue by YuanmingLeee** [cap-ntu/ML-Model-CI#125]
Current profiler fails in profiling on CPU @huangyz0918:
https://github.com/YuanmingLeee/ML-Model-CI/blob/0cb19ee10d05666f07fc4d3197e5bd0ada61f9b5/modelci/metrics/benchmark/metric.py#L132
This line fails, as there is no key named `'accelerators'` on CPU. Please help to fix this after this merge.

_Originally posted by @YuanmingLeee in https://github.com/cap-ntu/ML-Model-CI/pull/124/review_comment/create_

Full error logs:

```
Traceback (most recent call last):
  File "/home/lym/anaconda3/envs/modelci/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/controller/executor.py", line 83, in run
    dpr = profiler.diagnose(device=job.device)
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/hub/profiler.py", line 80, in diagnose
    result = self.inspector.run_model(server_name=self.server_name, device=device)
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/metrics/benchmark/metric.py", line 132, in run_model
    val_stats = [x for x in stats[-int(SLEEP_TIME + all_data_latency):] if
  File "/home/lym/Documents/PyCharmProjects/ML-Model-CI/modelci/metrics/benchmark/metric.py", line 133, in <listcomp>
    x['accelerators'][0]['duty_cycle'] is not 0]
KeyError: 0
```

**Comment by huangyz0918** [comment]
resolved in BMK, will integrate back when bmk is refactored and ready.
