### ISSUE TITLE
Mongodb initial pwd  is not set

### ISSUE THREAD

**Issue by univerone** [cap-ntu/ML-Model-CI#154]
#### Software and Hardware Versions 
ModelCI v1.x.x,
CUDA Version vx.x.x, 
GPU device used...

#### Problem description

After starting the service, MongoDB failed to start due to null pwd argument
```
2020-11-05 15:09:07,969 - ml-modelci Docker Container Manager - ERROR - Exception during starting MongoDB: "pwd" had the wrong type. Expected string, found null, full error: {'ok': 0.0, 'errmsg': '"pwd" had the wrong type. Expected string, found null', 'code': 14, 'codeName': 'TypeMismatch'}
2020-11-05 15:09:09,650 - ml-modelci Docker Container Manager - INFO - Container name=cadvisor-81293 started.
2020-11-05 15:09:10,795 - ml-modelci Docker Container Manager - INFO - Container name=dcgm-exporter-76327 started.
2020-11-05 15:09:11,527 - ml-modelci Docker Container Manager - INFO - gpu-metrics-exporter-86973 stared
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "~/project/github/ML-Model-CI/modelci/cli/__init__.py", line 36, in start
    __start__(gpu)
  File "~/project/github/ML-Model-CI/modelci/cli/__init__.py", line 28, in __start__
    if not container_conn.start():
  File "~/project/github/ML-Model-CI/modelci/utils/docker_container_manager.py", line 115, in start
    return self.connect()
  File "~/project/github/ML-Model-CI/modelci/utils/docker_container_manager.py", line 128, in connect
    self.mongo_port = all_labels[MODELCI_DOCKER_PORT_LABELS['mongo']]
KeyError: 'modelci.mongo.port'
```

#### Steps to Reproduce the Problem

```python
import modelci.cli 
modelci.cli.start()
```

#### Expected Behavior

program start without error

#### Other Information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

Setting a default password in 7th line of `modelci/config.py` make this error disappear

https://github.com/cap-ntu/ML-Model-CI/blob/ca81463f7b881dbdcdb15ad6dd47a39f7c0a0643/modelci/config.py#L7

**Comment by YuanmingLeee** [comment]
try this to setup env var
```shell script
source scripts/setup_env.sh
```

**Comment by univerone** [comment]
> try this to setup env var
> 
> ```shell
> source scripts/setup_env.sh
> ```

Thanks for your reply, it does help!
