### ISSUE TITLE
[Feat] support single-stage detection model

### ISSUE THREAD

**Issue by HuaizhengZhang** [cap-ntu/ML-Model-CI#166]
- [ ] https://github.com/Media-Smart/vedadet
- [x] check whether the converter can support this
- [x] improve the converter
- [ ] improve the profiler
- [ ] improve the deployer
- [x] add a new notebook

**Comment by HuaizhengZhang** [comment]
转不了的错误信息，详细记录

**Comment by univerone** [comment]
Convert TinaFace Model to ONNX format

## My script

```python
import os
import sys
from modelci.hub.converter import ONNXConverter
from modelci.types.bo import IOShape, Framework, Task, Engine
from modelci.hub.utils import generate_path
from modelci.types.trtis_objects import ModelInputFormat
import torch
from vedacore.misc import Config, load_weights
from vedadet.models import build_detector

if __name__ == "__main__":
    module_path = os.path.abspath(os.path.join('./repo'))
    if module_path not in sys.path:
        sys.path.append(module_path)
    cfg_dict = dict(
        model={
            "typename": "SingleStageDetector",
            "backbone": {
                "typename": "ResNet",
                "depth": 50,
                "num_stages": 4,
                "out_indices": (0, 1, 2, 3),
                "norm_cfg": {
                    "typename": "GN",
                    "num_groups": 32,
                    "requires_grad": True
                },
                "norm_eval": False,
                "dcn": {
                    "typename": "DCN",
                    "deformable_groups": 1,
                    "fallback_on_stride": False,
                },
                "stage_with_dcn": (False, False, True, True),
                "style": "pytorch",
            },
            "neck": [
                {
                    "typename": "FPN",
                    "in_channels": [256, 512, 1024, 2048],
                    "out_channels": 256,
                    "start_level": 0,
                    "add_extra_convs": "on_input",
                    "num_outs": 6,
                    "norm_cfg": {
                        "typename": "GN",
                        "num_groups": 32,
                        "requires_grad": True
                    },
                    "upsample_cfg": {
                        "mode": "bilinear"
                    },
                },
                {
                    "typename": "Inception",
                    "in_channel": 256,
                    "num_levels": 6,
                    "norm_cfg": {
                        "typename": "GN",
                        "num_groups": 32,
                        "requires_grad": True
                    },
                    "share": True,
                },
            ],
            "head": {
                "typename": "IoUAwareRetinaHead",
                "num_classes": 1,
                "num_anchors": 3,
                "in_channels": 256,
                "stacked_convs": 4,
                "feat_channels": 256,
                "norm_cfg": {
                    "typename": "GN",
                    "num_groups": 32,
                    "requires_grad": True
                },
                "use_sigmoid": True,
            },
        },
        weights={
            "filepath": "tinaface_r50_fpn_widerface.pth"
        }
    )
    cfg = Config(cfg_dict)
    model = build_detector(cfg.model)
    load_weights(model, cfg.weights.filepath)

    dev = torch.device("cpu")
    model.to(device)
    model.forward = model.forward_impl

    onnx_save_path = generate_path(
        model_name='ResNet50',
        framework=Framework.PYTORCH,
        task=Task.OBJECT_DETECTION,
        engine=Engine.ONNX,
        version=1
    )
    inputs = [IOShape([-1, 3, 800, 1344], dtype=float, name='INPUT__0', format=ModelInputFormat.FORMAT_NCHW)]
    ONNXConverter.from_torch_module(
        model,
        onnx_save_path,
        inputs=inputs,
    )
```

## Error Message


```
/home/sherry/project/github/ML-Model-CI/example/notebook/repo/vedadet/ops/dcn/deform_conv.py:107: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not all(map(lambda s: s > 0, output_size)):
Traceback (most recent call last):
  File "/home/sherry/project/github/ML-Model-CI/example/notebook/test.py", line 114, in <module>
    inputs=inputs,
  File "/home/sherry/project/github/ML-Model-CI/modelci/hub/converter.py", line 249, in from_torch_module
    **export_kwargs
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/onnx/utils.py", line 411, in _model_to_graph
    use_new_jit_passes)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/onnx/utils.py", line 379, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/onnx/utils.py", line 342, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_trace.py", line 1148, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_trace.py", line 130, in forward
    self._force_outplace,
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/sherry/project/github/ML-Model-CI/example/notebook/repo/vedadet/models/detectors/single_stage_detector.py", line 35, in forward_impl
    feats = self.backbone(x)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/sherry/project/github/ML-Model-CI/example/notebook/repo/vedadet/models/backbones/resnet.py", line 630, in forward
    x = res_layer(x)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/sherry/project/github/ML-Model-CI/example/notebook/repo/vedadet/models/backbones/resnet.py", line 297, in forward
    out = _inner_forward(x)
  File "/home/sherry/project/github/ML-Model-CI/example/notebook/repo/vedadet/models/backbones/resnet.py", line 274, in _inner_forward
    out = self.conv2(out)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/sherry/project/github/ML-Model-CI/example/notebook/repo/vedadet/ops/dcn/deform_conv.py", line 302, in forward
    self.dilation, self.groups, self.deformable_groups)
  File "/home/sherry/project/github/ML-Model-CI/example/notebook/repo/vedadet/ops/dcn/deform_conv.py", line 46, in forward
    raise NotImplementedError
NotImplementedError
```

**Comment by univerone** [comment]
The reason might be setting TinaFace model incorrectly, It's something related to the `cfg_dict` variable

**Comment by univerone** [comment]
# Attempt to Convert TinaFace into TorchScript

## My script

```python
from modelci.hub.converter import TorchScriptConverter
from modelci.types.bo import IOShape, Framework, Task, Engine
from modelci.hub.utils import generate_path
import torch
from vedacore.misc import Config, load_weights
from vedadet.models import build_detector

if __name__ == "__main__":
    cfg = Config.fromfile("repo/configs/trainval/tinaface/tinaface.py")
    model = build_detector(cfg.model)
    load_weights(model, "tinaface_r50_fpn_widerface.pth")

    device = 'cpu'
    model.to(device)
    model.forward = model.forward_impl

    shape = map(int, '3,800,1344'.split(','))
    dummy_input = torch.randn(1, *shape)
    onnx_save_path = generate_path(
        model_name='ResNet50',
        framework=Framework.PYTORCH,
        task=Task.OBJECT_DETECTION,
        engine=Engine.ONNX,
        version=1
    )
    dev = torch.device("cpu")
    model.to(dev)
    TorchScriptConverter.from_torch_module(
        model,
        onnx_save_path,
    )
```

## relevant Snippet

https://github.com/Media-Smart/vedadet/blob/main/vedadet/models/backbones/resnet.py#L264

## Error Log

```
/home/sherry/project/miniconda3/envs/modelci/bin/python /home/sherry/project/github/ML-Model-CI/example/notebook/test.py
Traceback (most recent call last):
  File "/home/sherry/project/github/ML-Model-CI/example/notebook/test.py", line 110, in <module>
    onnx_save_path,
  File "/home/sherry/project/github/ML-Model-CI/modelci/hub/converter.py", line 137, in from_torch_module
    traced = torch.jit.script(model)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_script.py", line 898, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 352, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 406, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_script.py", line 388, in _construct
    init_fn(script_module)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 388, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 406, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_script.py", line 388, in _construct
    init_fn(script_module)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 388, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 406, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_script.py", line 388, in _construct
    init_fn(script_module)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 388, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 364, in create_script_module_impl
    method_stubs = stubs_fn(nn_module)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 591, in infer_methods_to_compile
    stubs.append(make_stub_from_method(nn_module, method))
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 52, in make_stub_from_method
    return make_stub(func, method_name)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/_recursive.py", line 37, in make_stub
    ast = get_jit_def(func, name, self_name="RecursiveScriptModule")
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/frontend.py", line 221, in get_jit_def
    return build_def(ctx, fn_def, type_line, def_name, self_name=self_name)
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/frontend.py", line 255, in build_def
    build_stmts(ctx, body))
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/frontend.py", line 127, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/frontend.py", line 127, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/sherry/project/miniconda3/envs/modelci/lib/python3.7/site-packages/torch/jit/frontend.py", line 228, in __call__
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: function definitions aren't supported:
  File "/home/sherry/project/github/ML-Model-CI/example/notebook/repo/vedadet/models/backbones/resnet.py", line 264
        """Forward function."""

        def _inner_forward(x):
        ~~~ <--- HERE
            identity = x
```

**Comment by univerone** [comment]
Refer to the official documentation: https://github.com/Media-Smart/vedadet#deploy
Deformable Conv operations are unsupported for  model conversion.
