### ISSUE TITLE
Can't start service

### ISSUE THREAD

**Issue by QichenZheng** [cap-ntu/ML-Model-CI#252]
#### Software and Hardware Versions 
Ubuntu 18.04.6 LTS
CUDA 10.2
Docker version 19.03.6
#### Problem description
I follow the steps according to CONTRIBUTING.md and faced with the folllowing error.

(modelci) zqc@zqc-Lenovo-Y520-15IKBN:~/ML-Model-CI$ python modelci/cli/__init__.py service init
Traceback (most recent call last):
  File "modelci/cli/__init__.py", line 18, in <module>
    from modelci.cli import modelhub
  File "/home/zqc/ML-Model-CI/modelci/__init__.py", line 9, in <module>
    from . import hub
  File "/home/zqc/ML-Model-CI/modelci/hub/__init__.py", line 10, in <module>
    from .profiler import Profiler
  File "/home/zqc/ML-Model-CI/modelci/hub/profiler.py", line 13, in <module>
    from modelci.hub.client import CVONNXClient
  File "/home/zqc/ML-Model-CI/modelci/hub/client/__init__.py", line 8, in <module>
    from .onnx_client import CVONNXClient
  File "/home/zqc/ML-Model-CI/modelci/hub/client/onnx_client.py", line 18, in <module>
    from modelci.types.proto.service_pb2 import InferRequest
  File "/home/zqc/ML-Model-CI/modelci/types/proto/service_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

#### Steps to Reproduce the Problem

conda env create -f environment.yml
pip install torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2
pip install pytorch-lightning==0.8.5
pip install hummingbird-ml==0.2.1 torchviz==0.0.1
export PYTHONPATH="${PWD}"
python modelci/cli/__init__.py service init

#### Expected Behavior

Start Services

#### Other Information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by univerone** [comment]
Maybe you can refer to https://stackoverflow.com/a/61961016
