### ISSUE TITLE
Is it necessary to use linux system to do the installation

### ISSUE THREAD

**Issue by Lionjump0723** [cap-ntu/ML-Model-CI#255]
#### Software and Hardware Versions 

macOS 10.15.7
Docker version 19.03.12 

#### Problem description

I follow the steps according to README.md and faced with the folllowing error.

```
(base) cai@caideMacBook-Pro ~ % pip install git+git://github.com/cap-ntu/ML-Model-CI.git@master
WARNING: The directory '/Users/cai/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+git://github.com/cap-ntu/ML-Model-CI.git@master
  Cloning git://github.com/cap-ntu/ML-Model-CI.git (to revision master) to /private/var/folders/sm/fw6rnkrj471728596tyrh9jr0000gn/T/pip-req-build-s1uzb4r4
  Running command git clone -q git://github.com/cap-ntu/ML-Model-CI.git /private/var/folders/sm/fw6rnkrj471728596tyrh9jr0000gn/T/pip-req-build-s1uzb4r4
    ERROR: Command errored out with exit status 1:
     command: /Users/cai/opt/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sm/fw6rnkrj471728596tyrh9jr0000gn/T/pip-req-build-s1uzb4r4/setup.py'"'"'; __file__='"'"'/private/var/folders/sm/fw6rnkrj471728596tyrh9jr0000gn/T/pip-req-build-s1uzb4r4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/sm/fw6rnkrj471728596tyrh9jr0000gn/T/pip-req-build-s1uzb4r4/pip-egg-info
         cwd: /private/var/folders/sm/fw6rnkrj471728596tyrh9jr0000gn/T/pip-req-build-s1uzb4r4/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sm/fw6rnkrj471728596tyrh9jr0000gn/T/pip-req-build-s1uzb4r4/setup.py", line 51, in <module>
        stdout = subprocess.check_output(check_ubuntu_version_args, universal_newlines=True, shell=False)
      File "/Users/cai/opt/miniconda3/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/Users/cai/opt/miniconda3/lib/python3.7/subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Users/cai/opt/miniconda3/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/Users/cai/opt/miniconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)




    FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/lsb_release': '/usr/bin/lsb_release'
    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I've found on the website that lsb_release is specific to linux system like ubuntu. So I just want to confirm that it is necessary to install docker on a linux operating system machine to build the developing environment as well as the running environment. 

#### Steps to Reproduce the Problem
As above.

**Comment by jummp** [comment]
Yes, this way development is more convenient and efficient

It is recommended to use dual systems（mac/ubuntu18.04）

I first used the Ubuntu system on the virtual machine, but there was no real driver and graphics card. Finally, I installed a dual system to solve the problem.

**Comment by YuanmingLeee** [comment]
It is been fully tested on Ubuntu, but for mac it supposed to be ok. The error you meet is because there is no TensorRT version for mac. 
You are recommended to go through CONTRIBUTING.md to install the dev environment. There is some unexpected error when installing with pip. A PR is welcome if you can fix the pip install error.
