### ISSUE TITLE
docker.errors.APIError: 400 Client

### ISSUE THREAD

**Issue by PengZhang0** [cap-ntu/ML-Model-CI#259]
#### Software and Hardware Versions 
ModelCI v1.0.0, CUDA Version v10.1.243, GPU device used...

#### Problem description
Error in  "python modelci/cli/__init__.py service init"

#### Steps to Reproduce the Problem
python modelci/cli/__init__.py service init
(modelci) root@ML:/home/pengzhang/Learn/ML-Model-CI-master# python modelci/cli/__init__.py service init
2021-03-20 19:59:27,557 - ml-modelci Docker Container Manager - WARNING - Service with container name=cadvisor-18958 already started.
2021-03-20 19:59:27,557 - ml-modelci Docker Container Manager - WARNING - Service with container name=mongo-10147 already started.
Traceback (most recent call last):
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create?name=dcgm-exporter-66319

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "modelci/cli/__init__.py", line 42, in <module>
    typer_click_object()
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pengzhang/Learn/ML-Model-CI-master/modelci/cli/service.py", line 39, in start_leader_server
    if not container_conn.start():
  File "/home/pengzhang/Learn/ML-Model-CI-master/modelci/utils/docker_container_manager.py", line 110, in start
    self._start_dcgm_node_exporter()
  File "/home/pengzhang/Learn/ML-Model-CI-master/modelci/utils/docker_container_manager.py", line 279, in _start_dcgm_node_exporter
    **self.extra_container_kwargs
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/docker/models/containers.py", line 812, in run
    detach=detach, **kwargs)
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/pengzhang/miniconda3/envs/modelci/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=dcgm-exporter-66319: Bad Request ("Unknown runtime specified nvidia")

#### Expected Behavior
Successfully executed

#### Other Information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by YuanmingLeee** [comment]
Fixed via d3fadaf, pls rebase / pull and try again
