### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by swagshaw** [cap-ntu/ML-Model-CI#308]
#### Software and Hardware Versions 
ModelCI v1.x.x, CUDA Version vx.x.x, GPU device used...

#### Problem description
(mci) xiaoyang@xiaoyang-MS-7C86:/media/xiaoyang/File/ML-Model-CI$ modelci service init
2021-05-22 05:25:46.997569: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-05-22 05:25:46.997591: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-22 05:25:47,897 - ml-modelci Docker Container Manager - WARNING - Service already exist, found container name=gpu-metrics-exporter-70931.
2021-05-22 05:25:48,226 - ml-modelci Docker Container Manager - INFO - Service started.
2021-05-22 05:25:48,226 - ml-modelci Docker Container Manager - WARNING - Service already exist, found container name=dcgm-exporter-8849.
2021-05-22 05:25:48,427 - ml-modelci Docker Container Manager - INFO - Service started.
2021-05-22 05:25:48,427 - ml-modelci Docker Container Manager - WARNING - Service with container name=cadvisor-30226 already started.
2021-05-22 05:25:48,427 - ml-modelci Docker Container Manager - WARNING - Service with container name=mongo-51505 already started.
Traceback (most recent call last):
  File "/home/xiaoyang/anaconda3/envs/mci/bin/modelci", line 33, in <module>
    sys.exit(load_entry_point('modelci==1.0.0', 'console_scripts', 'modelci')())
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/modelci-1.0.0-py3.7.egg/modelci/cli/service.py", line 44, in start_leader_server
    app_start()
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/modelci-1.0.0-py3.7.egg/modelci/app/__init__.py", line 24, in start
    from modelci.app.main import _app_start_detach
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/modelci-1.0.0-py3.7.egg/modelci/app/main.py", line 17, in <module>
    from modelci.app.experimental.api import api_router as api_rounter_exp
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/modelci-1.0.0-py3.7.egg/modelci/app/experimental/api.py", line 10, in <module>
    from modelci.app.experimental.endpoints import cv_tuner
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/modelci-1.0.0-py3.7.egg/modelci/app/experimental/endpoints/cv_tuner.py", line 12, in <module>
    from modelci.experimental.model.model_structure import Structure, Operation
  File "/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/site-packages/modelci-1.0.0-py3.7.egg/modelci/experimental/model/model_structure.py", line 13, in <module>
    from typing import Optional, Union, Tuple, Dict, OrderedDict
ImportError: cannot import name 'OrderedDict' from 'typing' (/home/xiaoyang/anaconda3/envs/mci/lib/python3.7/typing.py)

#### Steps to Reproduce the Problem
I use setup.py to install modelci, and it was finished.
Then I try to start the service, I input "modelci service init" before this error occur.
#### Other Information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by swagshaw** [comment]
I update my python to 3.7.2, it fixed
